---
- name: Configure ELK VM with a docker setup
  hosts: elkserver
  remote_user: elkadmin
  become: true
  tasks:
    - name: Install Docker.io
      apt:
        update_cache: yes
        name: docker.io
        state: present
    - name: Install pip3
      apt:
        force_apt_get: yes
        name: python3-pip
        state: present
    - name: Install docker python modules
      pip:
        name: docker
        state: present

# increase vm memory, if required
    - name: More Memory for VM use
      sysctl:
        name: vm.max_map_count
        value: "262144"
        state: present
        reload: yes

#use docker container module to get ELK
    - name: Download / Launch docker ELK container
      docker_container:
        name: elk
        image: sebp/elk:761
        state: started
        restart_policy: always
        published_ports:
          - 5601:5601
          - 9200:9200
          - 5044:5044

    - name: Enable docker services at bootup
      systemd:
        name: docker
        enabled: yes
